// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.33.1
// source: protocol/chord.proto

package protocol

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Message definitions
type PingRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PingRequest) Reset() {
	*x = PingRequest{}
	mi := &file_protocol_chord_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PingRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PingRequest) ProtoMessage() {}

func (x *PingRequest) ProtoReflect() protoreflect.Message {
	mi := &file_protocol_chord_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PingRequest.ProtoReflect.Descriptor instead.
func (*PingRequest) Descriptor() ([]byte, []int) {
	return file_protocol_chord_proto_rawDescGZIP(), []int{0}
}

type PingResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PingResponse) Reset() {
	*x = PingResponse{}
	mi := &file_protocol_chord_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PingResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PingResponse) ProtoMessage() {}

func (x *PingResponse) ProtoReflect() protoreflect.Message {
	mi := &file_protocol_chord_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PingResponse.ProtoReflect.Descriptor instead.
func (*PingResponse) Descriptor() ([]byte, []int) {
	return file_protocol_chord_proto_rawDescGZIP(), []int{1}
}

type PutRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           string                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Value         []byte                 `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PutRequest) Reset() {
	*x = PutRequest{}
	mi := &file_protocol_chord_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PutRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PutRequest) ProtoMessage() {}

func (x *PutRequest) ProtoReflect() protoreflect.Message {
	mi := &file_protocol_chord_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PutRequest.ProtoReflect.Descriptor instead.
func (*PutRequest) Descriptor() ([]byte, []int) {
	return file_protocol_chord_proto_rawDescGZIP(), []int{2}
}

func (x *PutRequest) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *PutRequest) GetValue() []byte {
	if x != nil {
		return x.Value
	}
	return nil
}

type PutResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PutResponse) Reset() {
	*x = PutResponse{}
	mi := &file_protocol_chord_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PutResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PutResponse) ProtoMessage() {}

func (x *PutResponse) ProtoReflect() protoreflect.Message {
	mi := &file_protocol_chord_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PutResponse.ProtoReflect.Descriptor instead.
func (*PutResponse) Descriptor() ([]byte, []int) {
	return file_protocol_chord_proto_rawDescGZIP(), []int{3}
}

type GetRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           string                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetRequest) Reset() {
	*x = GetRequest{}
	mi := &file_protocol_chord_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRequest) ProtoMessage() {}

func (x *GetRequest) ProtoReflect() protoreflect.Message {
	mi := &file_protocol_chord_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRequest.ProtoReflect.Descriptor instead.
func (*GetRequest) Descriptor() ([]byte, []int) {
	return file_protocol_chord_proto_rawDescGZIP(), []int{4}
}

func (x *GetRequest) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

type GetResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Value         []byte                 `protobuf:"bytes,1,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetResponse) Reset() {
	*x = GetResponse{}
	mi := &file_protocol_chord_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetResponse) ProtoMessage() {}

func (x *GetResponse) ProtoReflect() protoreflect.Message {
	mi := &file_protocol_chord_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetResponse.ProtoReflect.Descriptor instead.
func (*GetResponse) Descriptor() ([]byte, []int) {
	return file_protocol_chord_proto_rawDescGZIP(), []int{5}
}

func (x *GetResponse) GetValue() []byte {
	if x != nil {
		return x.Value
	}
	return nil
}

type DeleteRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           string                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteRequest) Reset() {
	*x = DeleteRequest{}
	mi := &file_protocol_chord_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteRequest) ProtoMessage() {}

func (x *DeleteRequest) ProtoReflect() protoreflect.Message {
	mi := &file_protocol_chord_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteRequest.ProtoReflect.Descriptor instead.
func (*DeleteRequest) Descriptor() ([]byte, []int) {
	return file_protocol_chord_proto_rawDescGZIP(), []int{6}
}

func (x *DeleteRequest) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

type DeleteResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteResponse) Reset() {
	*x = DeleteResponse{}
	mi := &file_protocol_chord_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteResponse) ProtoMessage() {}

func (x *DeleteResponse) ProtoReflect() protoreflect.Message {
	mi := &file_protocol_chord_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteResponse.ProtoReflect.Descriptor instead.
func (*DeleteResponse) Descriptor() ([]byte, []int) {
	return file_protocol_chord_proto_rawDescGZIP(), []int{7}
}

type GetAllRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAllRequest) Reset() {
	*x = GetAllRequest{}
	mi := &file_protocol_chord_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAllRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAllRequest) ProtoMessage() {}

func (x *GetAllRequest) ProtoReflect() protoreflect.Message {
	mi := &file_protocol_chord_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAllRequest.ProtoReflect.Descriptor instead.
func (*GetAllRequest) Descriptor() ([]byte, []int) {
	return file_protocol_chord_proto_rawDescGZIP(), []int{8}
}

type GetAllResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	KeyValues     map[string][]byte      `protobuf:"bytes,1,rep,name=key_values,json=keyValues,proto3" json:"key_values,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"` // <-- Change from string to bytes
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAllResponse) Reset() {
	*x = GetAllResponse{}
	mi := &file_protocol_chord_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAllResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAllResponse) ProtoMessage() {}

func (x *GetAllResponse) ProtoReflect() protoreflect.Message {
	mi := &file_protocol_chord_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAllResponse.ProtoReflect.Descriptor instead.
func (*GetAllResponse) Descriptor() ([]byte, []int) {
	return file_protocol_chord_proto_rawDescGZIP(), []int{9}
}

func (x *GetAllResponse) GetKeyValues() map[string][]byte {
	if x != nil {
		return x.KeyValues
	}
	return nil
}

type GetPredecessorRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPredecessorRequest) Reset() {
	*x = GetPredecessorRequest{}
	mi := &file_protocol_chord_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPredecessorRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPredecessorRequest) ProtoMessage() {}

func (x *GetPredecessorRequest) ProtoReflect() protoreflect.Message {
	mi := &file_protocol_chord_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPredecessorRequest.ProtoReflect.Descriptor instead.
func (*GetPredecessorRequest) Descriptor() ([]byte, []int) {
	return file_protocol_chord_proto_rawDescGZIP(), []int{10}
}

type GetPredecessorResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Address       string                 `protobuf:"bytes,1,opt,name=address,proto3" json:"address,omitempty"`
	Pred          string                 `protobuf:"bytes,3,opt,name=pred,proto3" json:"pred,omitempty"`
	Successors    []string               `protobuf:"bytes,2,rep,name=successors,proto3" json:"successors,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPredecessorResponse) Reset() {
	*x = GetPredecessorResponse{}
	mi := &file_protocol_chord_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPredecessorResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPredecessorResponse) ProtoMessage() {}

func (x *GetPredecessorResponse) ProtoReflect() protoreflect.Message {
	mi := &file_protocol_chord_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPredecessorResponse.ProtoReflect.Descriptor instead.
func (*GetPredecessorResponse) Descriptor() ([]byte, []int) {
	return file_protocol_chord_proto_rawDescGZIP(), []int{11}
}

func (x *GetPredecessorResponse) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

func (x *GetPredecessorResponse) GetPred() string {
	if x != nil {
		return x.Pred
	}
	return ""
}

func (x *GetPredecessorResponse) GetSuccessors() []string {
	if x != nil {
		return x.Successors
	}
	return nil
}

type NotifyRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Address       string                 `protobuf:"bytes,1,opt,name=address,proto3" json:"address,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NotifyRequest) Reset() {
	*x = NotifyRequest{}
	mi := &file_protocol_chord_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NotifyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NotifyRequest) ProtoMessage() {}

func (x *NotifyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_protocol_chord_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NotifyRequest.ProtoReflect.Descriptor instead.
func (*NotifyRequest) Descriptor() ([]byte, []int) {
	return file_protocol_chord_proto_rawDescGZIP(), []int{12}
}

func (x *NotifyRequest) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

type NotifyResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NotifyResponse) Reset() {
	*x = NotifyResponse{}
	mi := &file_protocol_chord_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NotifyResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NotifyResponse) ProtoMessage() {}

func (x *NotifyResponse) ProtoReflect() protoreflect.Message {
	mi := &file_protocol_chord_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NotifyResponse.ProtoReflect.Descriptor instead.
func (*NotifyResponse) Descriptor() ([]byte, []int) {
	return file_protocol_chord_proto_rawDescGZIP(), []int{13}
}

type FindSuccessorRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            []byte                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FindSuccessorRequest) Reset() {
	*x = FindSuccessorRequest{}
	mi := &file_protocol_chord_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FindSuccessorRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FindSuccessorRequest) ProtoMessage() {}

func (x *FindSuccessorRequest) ProtoReflect() protoreflect.Message {
	mi := &file_protocol_chord_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FindSuccessorRequest.ProtoReflect.Descriptor instead.
func (*FindSuccessorRequest) Descriptor() ([]byte, []int) {
	return file_protocol_chord_proto_rawDescGZIP(), []int{14}
}

func (x *FindSuccessorRequest) GetId() []byte {
	if x != nil {
		return x.Id
	}
	return nil
}

type FindSuccessorRespons struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Adress        string                 `protobuf:"bytes,1,opt,name=adress,proto3" json:"adress,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FindSuccessorRespons) Reset() {
	*x = FindSuccessorRespons{}
	mi := &file_protocol_chord_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FindSuccessorRespons) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FindSuccessorRespons) ProtoMessage() {}

func (x *FindSuccessorRespons) ProtoReflect() protoreflect.Message {
	mi := &file_protocol_chord_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FindSuccessorRespons.ProtoReflect.Descriptor instead.
func (*FindSuccessorRespons) Descriptor() ([]byte, []int) {
	return file_protocol_chord_proto_rawDescGZIP(), []int{15}
}

func (x *FindSuccessorRespons) GetAdress() string {
	if x != nil {
		return x.Adress
	}
	return ""
}

var File_protocol_chord_proto protoreflect.FileDescriptor

const file_protocol_chord_proto_rawDesc = "" +
	"\n" +
	"\x14protocol/chord.proto\x12\x05chord\"\r\n" +
	"\vPingRequest\"\x0e\n" +
	"\fPingResponse\"4\n" +
	"\n" +
	"PutRequest\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\fR\x05value\"\r\n" +
	"\vPutResponse\"\x1e\n" +
	"\n" +
	"GetRequest\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\"#\n" +
	"\vGetResponse\x12\x14\n" +
	"\x05value\x18\x01 \x01(\fR\x05value\"!\n" +
	"\rDeleteRequest\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\"\x10\n" +
	"\x0eDeleteResponse\"\x0f\n" +
	"\rGetAllRequest\"\x93\x01\n" +
	"\x0eGetAllResponse\x12C\n" +
	"\n" +
	"key_values\x18\x01 \x03(\v2$.chord.GetAllResponse.KeyValuesEntryR\tkeyValues\x1a<\n" +
	"\x0eKeyValuesEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\fR\x05value:\x028\x01\"\x17\n" +
	"\x15GetPredecessorRequest\"f\n" +
	"\x16GetPredecessorResponse\x12\x18\n" +
	"\aaddress\x18\x01 \x01(\tR\aaddress\x12\x12\n" +
	"\x04pred\x18\x03 \x01(\tR\x04pred\x12\x1e\n" +
	"\n" +
	"successors\x18\x02 \x03(\tR\n" +
	"successors\")\n" +
	"\rNotifyRequest\x12\x18\n" +
	"\aaddress\x18\x01 \x01(\tR\aaddress\"\x10\n" +
	"\x0eNotifyResponse\"&\n" +
	"\x14FindSuccessorRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\fR\x02id\".\n" +
	"\x14FindSuccessorRespons\x12\x16\n" +
	"\x06adress\x18\x01 \x01(\tR\x06adress2\xd3\x03\n" +
	"\x05Chord\x12/\n" +
	"\x04Ping\x12\x12.chord.PingRequest\x1a\x13.chord.PingResponse\x12,\n" +
	"\x03Put\x12\x11.chord.PutRequest\x1a\x12.chord.PutResponse\x12,\n" +
	"\x03Get\x12\x11.chord.GetRequest\x1a\x12.chord.GetResponse\x125\n" +
	"\x06Delete\x12\x14.chord.DeleteRequest\x1a\x15.chord.DeleteResponse\x125\n" +
	"\x06GetAll\x12\x14.chord.GetAllRequest\x1a\x15.chord.GetAllResponse\x12M\n" +
	"\x0eGetPredecessor\x12\x1c.chord.GetPredecessorRequest\x1a\x1d.chord.GetPredecessorResponse\x12I\n" +
	"\rFindSuccessor\x12\x1b.chord.FindSuccessorRequest\x1a\x1b.chord.FindSuccessorRespons\x125\n" +
	"\x06Notify\x12\x14.chord.NotifyRequest\x1a\x15.chord.NotifyResponseB\fZ\n" +
	"./protocolb\x06proto3"

var (
	file_protocol_chord_proto_rawDescOnce sync.Once
	file_protocol_chord_proto_rawDescData []byte
)

func file_protocol_chord_proto_rawDescGZIP() []byte {
	file_protocol_chord_proto_rawDescOnce.Do(func() {
		file_protocol_chord_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_protocol_chord_proto_rawDesc), len(file_protocol_chord_proto_rawDesc)))
	})
	return file_protocol_chord_proto_rawDescData
}

var file_protocol_chord_proto_msgTypes = make([]protoimpl.MessageInfo, 17)
var file_protocol_chord_proto_goTypes = []any{
	(*PingRequest)(nil),            // 0: chord.PingRequest
	(*PingResponse)(nil),           // 1: chord.PingResponse
	(*PutRequest)(nil),             // 2: chord.PutRequest
	(*PutResponse)(nil),            // 3: chord.PutResponse
	(*GetRequest)(nil),             // 4: chord.GetRequest
	(*GetResponse)(nil),            // 5: chord.GetResponse
	(*DeleteRequest)(nil),          // 6: chord.DeleteRequest
	(*DeleteResponse)(nil),         // 7: chord.DeleteResponse
	(*GetAllRequest)(nil),          // 8: chord.GetAllRequest
	(*GetAllResponse)(nil),         // 9: chord.GetAllResponse
	(*GetPredecessorRequest)(nil),  // 10: chord.GetPredecessorRequest
	(*GetPredecessorResponse)(nil), // 11: chord.GetPredecessorResponse
	(*NotifyRequest)(nil),          // 12: chord.NotifyRequest
	(*NotifyResponse)(nil),         // 13: chord.NotifyResponse
	(*FindSuccessorRequest)(nil),   // 14: chord.FindSuccessorRequest
	(*FindSuccessorRespons)(nil),   // 15: chord.FindSuccessorRespons
	nil,                            // 16: chord.GetAllResponse.KeyValuesEntry
}
var file_protocol_chord_proto_depIdxs = []int32{
	16, // 0: chord.GetAllResponse.key_values:type_name -> chord.GetAllResponse.KeyValuesEntry
	0,  // 1: chord.Chord.Ping:input_type -> chord.PingRequest
	2,  // 2: chord.Chord.Put:input_type -> chord.PutRequest
	4,  // 3: chord.Chord.Get:input_type -> chord.GetRequest
	6,  // 4: chord.Chord.Delete:input_type -> chord.DeleteRequest
	8,  // 5: chord.Chord.GetAll:input_type -> chord.GetAllRequest
	10, // 6: chord.Chord.GetPredecessor:input_type -> chord.GetPredecessorRequest
	14, // 7: chord.Chord.FindSuccessor:input_type -> chord.FindSuccessorRequest
	12, // 8: chord.Chord.Notify:input_type -> chord.NotifyRequest
	1,  // 9: chord.Chord.Ping:output_type -> chord.PingResponse
	3,  // 10: chord.Chord.Put:output_type -> chord.PutResponse
	5,  // 11: chord.Chord.Get:output_type -> chord.GetResponse
	7,  // 12: chord.Chord.Delete:output_type -> chord.DeleteResponse
	9,  // 13: chord.Chord.GetAll:output_type -> chord.GetAllResponse
	11, // 14: chord.Chord.GetPredecessor:output_type -> chord.GetPredecessorResponse
	15, // 15: chord.Chord.FindSuccessor:output_type -> chord.FindSuccessorRespons
	13, // 16: chord.Chord.Notify:output_type -> chord.NotifyResponse
	9,  // [9:17] is the sub-list for method output_type
	1,  // [1:9] is the sub-list for method input_type
	1,  // [1:1] is the sub-list for extension type_name
	1,  // [1:1] is the sub-list for extension extendee
	0,  // [0:1] is the sub-list for field type_name
}

func init() { file_protocol_chord_proto_init() }
func file_protocol_chord_proto_init() {
	if File_protocol_chord_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_protocol_chord_proto_rawDesc), len(file_protocol_chord_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   17,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_protocol_chord_proto_goTypes,
		DependencyIndexes: file_protocol_chord_proto_depIdxs,
		MessageInfos:      file_protocol_chord_proto_msgTypes,
	}.Build()
	File_protocol_chord_proto = out.File
	file_protocol_chord_proto_goTypes = nil
	file_protocol_chord_proto_depIdxs = nil
}
